src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;

#[ORM\Entity(repositoryClass: SortieRepository::class)]
class Sortie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'isRegister')]
    private Collection $users;

    #[ORM\ManyToOne(inversedBy: 'organizer')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    private ?Etat $etat = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    private ?Campus $place = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    private ?Lieu $address = null;

    #[ORM\Column(length: 30)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateHeureDebut = null;

    #[ORM\Column]
    private ?int $duration = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateLimite = null;

    #[ORM\Column]
    private ?int $registerLimit = null;

    #[ORM\Column(length: 255)]
    private ?string $infos = null;

    #[ORM\Column(length: 255)]
    private ?string $motifAnnulation = "Aucun motif d'annulation";

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getMotifAnnulation(): ?string
    {
        return $this->motifAnnulation;
    }

    public function setMotifAnnulation(?string $motifAnnulation): self
    {
        $this->motifAnnulation = $motifAnnulation;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addIsRegister($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeIsRegister($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getPlace(): ?Campus
    {
        return $this->place;
    }

    public function setPlace(?Campus $place): static
    {
        $this->place = $place;

        return $this;
    }

    public function getAddress(): ?Lieu
    {
        return $this->address;
    }

    public function setAddress(?Lieu $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?Ville
    {
        return $this->address ? $this->address->getCity() : null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateHeureDebut(): ?\DateTimeInterface
    {
        return $this->dateHeureDebut;
    }

    public function setDateHeureDebut(\DateTimeInterface $dateHeureDebut): static
    {
        $this->dateHeureDebut = $dateHeureDebut;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDateLimite(): ?\DateTimeInterface
    {
        return $this->dateLimite;
    }

    public function setDateLimite(\DateTimeInterface $dateLimite): static
    {
        $this->dateLimite = $dateLimite;

        return $this;
    }

    public function getRegisterLimit(): ?int
    {
        return $this->registerLimit;
    }

    public function setRegisterLimit(int $registerLimit): static
    {
        $this->registerLimit = $registerLimit;

        return $this;
    }

    public function getInfos(): ?string
    {
        return $this->infos;
    }

    public function setInfos(string $infos): static
    {
        $this->infos = $infos;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity]
#[UniqueEntity(fields: ['username'], message: 'Ce pseudo est déjà utilisé.')]
#[UniqueEntity(fields: ['email'], message: 'Cet email est déjà utilisé.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 30)]
    private ?string $firstName = null;

    #[ORM\Column(length: 30)]
    private ?string $name = null;

    #[ORM\Column(length: 20)]
    private ?string $phone = null;

    #[ORM\Column(nullable: false)]
    private ?bool $active = true;

    #[ORM\ManyToMany(targetEntity: Sortie::class, inversedBy: 'users')]
    private Collection $isRegister;

    #[ORM\OneToMany(targetEntity: Sortie::class, mappedBy: 'user')]
    private Collection $organizer;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Campus $isAttachedTo = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(nullable: true)]
    private ?string $profilePicture = null;

    public function __construct()
    {
        $this->isRegister = new ArrayCollection();
        $this->organizer = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): static
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getIsRegister(): Collection
    {
        return $this->isRegister;
    }

    public function addIsRegister(Sortie $isRegister): static
    {
        if (!$this->isRegister->contains($isRegister)) {
            $this->isRegister->add($isRegister);
        }

        return $this;
    }

    public function removeIsRegister(Sortie $isRegister): static
    {
        $this->isRegister->removeElement($isRegister);

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getOrganizer(): Collection
    {
        return $this->organizer;
    }

    public function addOrganizer(Sortie $organizer): static
    {
        if (!$this->organizer->contains($organizer)) {
            $this->organizer->add($organizer);
            $organizer->setUser($this);
        }

        return $this;
    }

    public function removeOrganizer(Sortie $organizer): static
    {
        if ($this->organizer->removeElement($organizer)) {
            // set the owning side to null (unless already changed)
            if ($organizer->getUser() === $this) {
                $organizer->setUser(null);
            }
        }

        return $this;
    }

    public function getIsAttachedTo(): ?Campus
    {
        return $this->isAttachedTo;
    }

    public function setIsAttachedTo(?Campus $isAttachedTo): static
    {
        $this->isAttachedTo = $isAttachedTo;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->isAttachedTo;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profilePicture;
    }

    public function setProfilePicture(?string $profilePicture): self
    {
        $this->profilePicture = $profilePicture;

        return $this;
    }

}

templates/sortie_create/_delete_form.html.twig
<form method="post" action="{{ path('app_sortie_create_delete', {'id': sortie.id}) }}" onsubmit="return confirm('Êtes vous sûr de vouloir supprimer la sortie ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sortie.id) }}">
    <button class="btn btn-danger">Supprimer la sortie</button>
</form>

templates/sortie_create/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/sortie_create/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Sortie{% endblock %}

{% block body %}
    <h1>Modifier les informations de : {{ sortie.nom }}</h1>

    <form method="post">
        {{ form_start(form) }}
        <div>
            {{ form_label(form.nom) }}
            {{ form_widget(form.nom) }}
            {{ form_errors(form.nom) }}
        </div>
        <div>
            {{ form_label(form.dateHeureDebut) }}
            {{ form_widget(form.dateHeureDebut) }}
            {{ form_errors(form.dateHeureDebut) }}
        </div>
        <div>
            {{ form_label(form.duration) }}
            {{ form_widget(form.duration) }}
            {{ form_errors(form.duration) }}
        </div>
        <div>
            {{ form_label(form.dateLimite) }}
            {{ form_widget(form.dateLimite) }}
            {{ form_errors(form.dateLimite) }}
        </div>
        <div>
            {{ form_label(form.registerLimit) }}
            {{ form_widget(form.registerLimit) }}
            {{ form_errors(form.registerLimit) }}
        </div>
        <div>
            {{ form_label(form.infos) }}
            {{ form_widget(form.infos) }}
            {{ form_errors(form.infos) }}
        </div>
        <p>Campus : {{ app.user.campus.nom }}</p>
        <div>
            {{ form_label(form.address) }}
            {{ form_widget(form.address) }}
            {{ form_errors(form.address) }}
        </div>
        {{ form_end(form) }}
    </form>

    <a href="{{ path('app_home') }}" class="btn btn-primary">Retour à l'accueil</a>

    {{ include('sortie_create/_delete_form.html.twig') }}
    {% for flashMessage in app.flashes('error') %}
        <div class="alert alert-danger">{{ flashMessage }}</div>
    {% endfor %}
{% endblock %}

templates/sortie_create/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sortie index{% endblock %}

{% block body %}

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>DateHeureDebut</th>
                <th>Duration</th>
                <th>DateLimite</th>
                <th>RegisterLimit</th>
                <th>Infos</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sortie in sorties %}
            <tr>
                <td>{{ sortie.id }}</td>
                <td>{{ sortie.nom }}</td>
                <td>{{ sortie.dateHeureDebut ? sortie.dateHeureDebut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ sortie.duration }}</td>
                <td>{{ sortie.dateLimite ? sortie.dateLimite|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ sortie.registerLimit }}</td>
                <td>{{ sortie.infos }}</td>
                <td>
                    <a href="{{ path('app_sortie_create_show', {'id': sortie.id}) }}">show</a>
                    <a href="{{ path('app_sortie_create_edit', {'id': sortie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_sortie_create_new') }}">Create new</a>
{% endblock %}

templates/sortie_create/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une sortie{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="text-center mb-4">Créer une sortie</h1>

        {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}

        <div class="mb-3">
            {{ form_label(form.nom, 'Nom de la sortie', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.nom, {'attr': {'class': 'form-text text-danger'}}) }}
        </div>
        <div class="mb-3">
            {{ form_label(form.dateHeureDebut, 'Date et heure de début', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.dateHeureDebut, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.dateHeureDebut, {'attr': {'class': 'form-text text-danger'}}) }}
        </div>
        <div class="mb-3">
            {{ form_label(form.duration, 'Durée', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.duration, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.duration, {'attr': {'class': 'form-text text-danger'}}) }}
        </div>
        <div class="mb-3">
            {{ form_label(form.dateLimite, 'Date limite d\'inscription', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.dateLimite, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.dateLimite, {'attr': {'class': 'form-text text-danger'}}) }}
        </div>
        <div class="mb-3">
            {{ form_label(form.registerLimit, 'Nombre de places', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.registerLimit, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.registerLimit, {'attr': {'class': 'form-text text-danger'}}) }}
        </div>
        <div class="mb-3">
            {{ form_label(form.infos, 'Informations', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.infos, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.infos, {'attr': {'class': 'form-text text-danger'}}) }}
        </div>
        <div class="mb-3">
            <label class="form-label">Campus : {{ app.user.campus.nom }}</label>
        </div>
        <div class="mb-3">
            {{ form_label(form.address, 'Adresse', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.address, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.address, {'attr': {'class': 'form-text text-danger'}}) }}
        </div>
        <div class="form-group text-center">
            {{ form_widget(form.enregistrer, {'attr': {'class': 'btn btn-primary mr-2'}}) }}
            {{ form_widget(form.publier, {'attr': {'class': 'btn btn-success mr-2'}}) }}
            <a href="{{ path('app_home') }}" class="btn btn-secondary">Retour à l'accueil</a>
        </div>

        {{ form_end(form) }}

        {% for flashMessage in app.flashes('error') %}
            <div class="alert alert-danger">{{ flashMessage }}</div>
        {% endfor %}
    </div>
{% endblock %}

templates/sortie_create/show.html.twig
{# templates/sortie/detail.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Affichage d'une sortie{% endblock %}

{% block body %}
    <div class="container my-5">
        <h1 class="mb-4 text-center">Afficher une sortie</h1>

        <!-- Section principale avec deux colonnes -->
        <div class="row mb-4">
            <!-- Colonne de gauche -->
            <div class="col-md-6">
                <div class="p-3 bg-light border">
                    <p><strong>Nom de la sortie:</strong> {{ sortie.nom }}</p>
                    <p><strong>Date et heure de la sortie:</strong> {{ sortie.dateHeureDebut|date('d/m/Y H:i') }}</p>
                    <p><strong>Date limite d'inscription:</strong> {{ sortie.dateLimite|date('d/m/Y H:i') }}</p>
                    <p><strong>Utilisateurs inscrits:</strong> {{ sortie.users|length }} / {{ sortie.registerLimit }}</p>
                    <p><strong>Durée (en minutes):</strong> {{ sortie.duration }}</p>
                    <p><strong>Organisateur:</strong>
                        <a href="{{ path('app_user_profile', {'username': sortie.user.username}) }}">
                            {{ sortie.user.username }}
                        </a>
                    </p>
                    {% if sortie.etat.libelle == 'Annulée' %}
                        <p><strong>Motif d'annulation:</strong> {{ sortie.motifAnnulation }}</p>
                    {% elseif sortie.dateHeureDebut > date('now') and sortie.users.contains(app.user) %}
                        <p><strong>Je suis déjà inscrit à cette sortie : </strong></p>
                        <a href="{{ path('app_sortie_desistement', {'id': sortie.id}) }}"
                           class="btn btn-warning"
                           onclick="return confirm('Êtes-vous sûr de vouloir vous désister de cette sortie ?');">
                            Se désister
                        </a>
                        {% elseif sortie.etat.libelle == 'Ouverte' and sortie.dateLimite > date('now') and sortie.dateHeureDebut > date('now') and not sortie.users.contains(app.user) %}
                            <p><strong>Je ne suis pas inscrit à cette sortie : </strong></p>
                                <a href="{{ path('app_sortie_inscription', {'id': sortie.id}) }}"
                                   class="btn btn-primary"
                                   onclick="return confirm('Êtes-vous sûr de vouloir vous inscrire à cette sortie ?');">
                                    S'inscrire
                                </a>
                    {% endif %}
                </div>
            </div>

            <!-- Colonne de droite -->
            <div class="col-md-6">
                <div class="p-3 bg-light border">
                    <p><strong>Campus:</strong> {{ sortie.place.nom }}</p>
                    <p><strong>Ville:</strong> {{ sortie.address.city.nom }}</p>
                    <p><strong>Lieu:</strong> {{ sortie.address.nom }}</p>
                    <p><strong>Rue:</strong> {{ sortie.address.address }}</p>
                    <p><strong>Code postal:</strong> {{ sortie.address.city.codePostal }}</p>
                    <p><strong>Latitude / Longitude:</strong> {{ sortie.address.latitude }} / {{ sortie.address.longitude }}</p>
                </div>
            </div>
        </div>

        <!-- Section description et infos -->
        <div class="row mb-4">
            <div class="col">
                <div class="p-3 bg-light border">
                    <h2>Description et infos</h2>
                    <p>{{ sortie.infos }}</p>
                </div>
            </div>
        </div>

        <!-- Tableau des participants -->
        <div class="row">
            <div class="col">
                <div class="p-3 bg-light border">
                    <h2>Liste des participants inscrits</h2>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Pseudo</th>
                            <th>Nom</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in sortie.users %}
                            <tr>
                                <td><a href="{{ path('app_user_profile', {'username': user.username}) }}">{{ user.username }}</a></td>
                                <td>{{ user.name }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}